import { LANG_KEY } from './lang-keys';

// lang-en.ts
export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS: { [key in LANG_KEY]?: string } = {
  [LANG_KEY.CREATE]: 'Create',
  [LANG_KEY.CREATE_PROFESSION]: 'Create Profession',
  [LANG_KEY.NAME]: 'NAME',
  [LANG_KEY.FILTER_BY_NAME]: 'FILTER BY NAME',
  [LANG_KEY.UPDATE]: 'Update',
  [LANG_KEY.DELETE]: 'Delete',
  [LANG_KEY.SUBMIT]: 'Submit',
  [LANG_KEY.USERNAME]: 'Username',
  [LANG_KEY.PASSWORD]: 'Password',
  [LANG_KEY.LOGOUT]: 'Logout',
  [LANG_KEY.WORKERS]: 'Workers',
  [LANG_KEY.PROFESSIONS]: 'Professions',
  [LANG_KEY.TRANSACTIONS]: 'Transactions',
  [LANG_KEY.FILTER_BY]: 'Filter By',
  [LANG_KEY.REQUESTS]: 'Requests',
  [LANG_KEY.CUSTOMER_LOCATION]: 'Customer Location',
  [LANG_KEY.CUSTOMER_NAME]: 'Customer Name',
  [LANG_KEY.PROFESSION]: 'Profession',
  [LANG_KEY.DESCRIPTION]: 'Description',
  [LANG_KEY.DATE]: 'Date',
  [LANG_KEY.CREATE_WORKER]: 'Create Worker',
  [LANG_KEY.USERS]: 'Users',
  [LANG_KEY.FIRST_NAME]: 'First Name',
  [LANG_KEY.MIDDEL_NAME]: 'Middel Name',
  [LANG_KEY.LAST_NAME]: 'Last Name',
  [LANG_KEY.MOTHER_NAME]: 'Mother Name',
  [LANG_KEY.BLOOD_TYPE]: 'Blood Type',
  [LANG_KEY.PERSONAL_ID]: 'Personal Id',
  [LANG_KEY.DATE_OF_BIRTH]: 'Date Of Birth',
  [LANG_KEY.PROFESSION_NAME]: 'Profession Name',
  [LANG_KEY.LOGIN]: 'Login',
  [LANG_KEY.PLATE_NUMBER]: 'Plate Number',
  [LANG_KEY.CHECK]: 'Check',
  [LANG_KEY.N0_VEHICLE_FOUND_CREATE_ONE]: 'No Vehicle Found Create One',
  [LANG_KEY.CREATE_NEW_VEHICLE]: 'Create New Vehicle',
  [LANG_KEY.VEHICLE_INFO]: 'Vehicle Info',
  [LANG_KEY.VEHICLE_NAME]: 'Vehicle Name',
  [LANG_KEY.TYPE]: 'Type',
  [LANG_KEY.NUMBER_OF_SEATS]: 'Number Of Seats',
  [LANG_KEY.WEIGHT]: 'Weight',
  [LANG_KEY.DETAILS]: 'Details',
  [LANG_KEY.NEXT]: 'Next',
  [LANG_KEY.ADD_NEW_VEHICLE]: 'Add New Vehicle',
  [LANG_KEY.CUSTOMER]: 'Customer',
  [LANG_KEY.CREATE_NEW_PERSON]: 'Create New Person',
  [LANG_KEY.CUSTOMER_INFO]: 'Customer Info',
  [LANG_KEY.FULL_NAME]: 'Full Name',
  [LANG_KEY.ADD_NEW_CUSTOMER]: 'Add  New Customer',
  [LANG_KEY.SOURCE]: 'Source',
  [LANG_KEY.DESTINATION]: 'Destination',
  [LANG_KEY.TOWING_TICKET_DETAILS]: 'Towing Ticket Details',
  [LANG_KEY.ESTIMATED_TIME]: 'Estimated Time',
  [LANG_KEY.ID]: 'ID',
  [LANG_KEY.ROAD_TYPE]: 'Road Type',
  [LANG_KEY.DATE_TIME]: 'Date Time',
  [LANG_KEY.SOURCE_NAME]: 'Source Name',
  [LANG_KEY.DESTINATION_NAME]: 'Destination Name',
  [LANG_KEY.SHOW_DETAILS]: 'Show Details',
  [LANG_KEY.ADD_REQUEST]: 'Add Request',
  [LANG_KEY.IMPORT_USER_POLICIES]: 'Import User Policies',
  [LANG_KEY.ADD_AGREEMENT]: 'Add Agreement',
  [LANG_KEY.COMPANY]: 'Company',
  [LANG_KEY.BILLING_TYPE]: 'Billing Type',
  [LANG_KEY.MAX_TRANSACTION_PER_DAY]: 'Max Transaction Per Day',
  [LANG_KEY.MAX_KM_BY_TRANSACTION]: 'Max km per Transaction',
  [LANG_KEY.MECHANICAL_SERVICE_FEES]: 'Mechanical Service Fees',
  [LANG_KEY.ACCIDENT_SERVICE_FEES]: 'Accident Service Fees',
  [LANG_KEY.EDIT]: 'Edit',
  [LANG_KEY.AGREEMENT_TYPE]: 'Agreement Type',
  [LANG_KEY.TOTAL_DISTANCE]: 'Total Distance',
  [LANG_KEY.TOTAL_COST]: 'Total Cost',
  [LANG_KEY.INSURANCE_COMPANY]: 'Insurance Company',
  [LANG_KEY.CREATE_TOWDRIVER]: 'Create Towdriver',
  [LANG_KEY.INSURANCE_AGREEMENTS]: 'Insurance Agreements',
  [LANG_KEY.TOWING_PARTNERS_AGREEMENTS]: 'Towing Partners Agreements',
  [LANG_KEY.BILLING_CONFIGURATION]: 'Billing Configration',
  [LANG_KEY.REPORTING]: 'Reporting',
  [LANG_KEY.SELECT_COMPANY]: 'Select Company',
  [LANG_KEY.PAYMENT_TYPE]: 'Payment Type',
  [LANG_KEY.POSTPAID_MODE]: 'PostPaid Mode',
  [LANG_KEY.PREPAID]: 'PrePaid',
  [LANG_KEY.POSTPAID]: 'PostPaid',
  [LANG_KEY.FIXED]: 'Fixed',
  [LANG_KEY.DYNAMIC]: 'Dynamic',
  [LANG_KEY.FIXED_FEES_PER_POLICY]: 'Fixed Fees Per Policy',
  [LANG_KEY.FIXED_FEES_PER_TRANSACTION]: 'Fixed Fees Per Transaction',
  [LANG_KEY.UNLIMITED]: 'Unlimited',
  [LANG_KEY.MAX_ALLOWED_TRANSACTIONS_PER_DAY]: 'Max Allow Transaction Per Day',
  [LANG_KEY.MAX_ALLOWED_TRANSACTIONS_PER_YEAR]: 'Max Allow Transaction Per Year',
  [LANG_KEY.MAX_KM_TRANSACTION]: 'Max Km by Transaction',
  [LANG_KEY.MECHANICAL_SERVICE_TYPE_FEES]: 'Mechanical Service Type Fees',
  [LANG_KEY.ACCIDENT_SERVICE_TYPE_FEES]: 'Accident Service Type Fees',
  [LANG_KEY.SAVE]: 'Save',
  [LANG_KEY.CATEGORIES]: 'Categories',
  [LANG_KEY.MINIMUM_TRANSACTION_FEES]: 'Minimum Transaction Fees',
  [LANG_KEY.FEES_PER_KM]: 'Fees Per Km',
  [LANG_KEY.MAXIMUM_COVERED_DISTANCE]: 'Maximum Covered Distance',
  [LANG_KEY.EASY_ROAD_NAVIGATION_FEES]: 'Easy Road Navigation Fees',
  [LANG_KEY.MEDIUM_ROAD_NAVIGATION_FEES]: 'Medium Road Navigation Fees',
  [LANG_KEY.DIFFICULT_ROAD_NAVIGATION_FEES]: 'Difficult Road Navigation Fees',
  [LANG_KEY.ADD]: 'Add',
  [LANG_KEY.LATE_NIGHT_TRANSACTION_FEES]: 'Late Night Transaction Fees',
  [LANG_KEY.VEHICLE_OVER_M_TYPE_FEES]: 'Vehicle Over-m Type Fees',
  [LANG_KEY.VEHICLE_PRIVATE_TYPE_FEES]: 'Vehicle Private Type Fees',
  [LANG_KEY.VACATION_TRANSACTION_FEES]: 'Vacation Transaction Fees',
  [LANG_KEY.ADD_SPECIFIC_BILLING_RULE]: 'Add Specific Billing Rule',
  [LANG_KEY.CATEGORY]: 'Category',
  [LANG_KEY.TRANSACTION_FEES]: 'Transaction Fees',
  [LANG_KEY.MAXIMUM_DISTANCE]: 'Maximum Distance',
  [LANG_KEY.EASY_ROAD]: 'Easy Road',
  [LANG_KEY.MEDIUM_ROAD]: 'Medium Road',
  [LANG_KEY.DIFFICULT_ROAD]: 'Difficult Road',
  [LANG_KEY.VEHICLE_MODEL]: 'Vehicle Model',
  [LANG_KEY.VEHICLE_BRAND]: 'Vehicle Brand',
  [LANG_KEY.VEHICLE_TYPE]: 'Vehicle Type',
  [LANG_KEY.VEHICLE_DETAILS]: 'Vehicle Details',
  [LANG_KEY.VEHICLE]: 'Vehicle',
  [LANG_KEY.PARTY_TYPE]: 'Party Type',
  [LANG_KEY.PERSON]: 'Person',
  [LANG_KEY.TOW_DRIVER_RESPONSE]: 'Tow Driver Response',
  [LANG_KEY.SEND_BROADCAST]: 'Send BroadCast',
  [LANG_KEY.COMPANY_DRIVERS]: 'Company Drivers',
  [LANG_KEY.FREELANCE_DRIVERS]: 'Freelance Drivers',
  [LANG_KEY.PARTNERS_DRIVERS]: 'Partners Drivers',
  [LANG_KEY.ARE_YOU_SURE_YOU_WANT_TO_LOCK_THIS_RWQUEST_TO]: 'Are you sure you want to lock this request to',
  [LANG_KEY.CANCEL]: 'Cancel',
  [LANG_KEY.YES]: 'yes',
  [LANG_KEY.TICKET_INFO]: 'Ticket Info',
  [LANG_KEY.WHEEL_STATUS]: 'Wheel Status',
  [LANG_KEY.ADD_TICKET]: 'Add Ticket',
  [LANG_KEY.ROAD_ENVIRONMENT]: 'Road Environment',
  [LANG_KEY.EASY]: 'Easy',
  [LANG_KEY.MEDIUM]: 'Medium',
  [LANG_KEY.DIFFICULT]: 'Difficult',
  [LANG_KEY.VACTION]: 'Vaction',
  [LANG_KEY.LATE_NIGHT]: 'Late Night',
  [LANG_KEY.ESTIMATED_FEES]: 'Estimated Fees',
  [LANG_KEY.DISCOUNT]: 'Discount',
  [LANG_KEY.ADDITIONAL_COST]: 'Additional Cost',
  [LANG_KEY.VEHICLE_ON_WHEEL]: 'Vehicle On Wheels',
  [LANG_KEY.IMPORT]: 'Import',
  [LANG_KEY.END_DATE]: 'End Date',
  [LANG_KEY.START_DATE]: 'Start Date',
  [LANG_KEY.CAR_CATEGORY]: 'Car Category',
  [LANG_KEY.POLICY_TYPE]: 'Policy Type',
  [LANG_KEY.POLICY_NUMBER]: 'Policy Number',
  [LANG_KEY.USER_POLICIES]: 'User Policies',
  [LANG_KEY.SELECT_FILE]: 'Select File',
  [LANG_KEY.EXCEL_FIELDS]: 'Excel Fields',
  [LANG_KEY.TOWING_POLICIES_COLUMN]: 'Towing Policies Column',
  [LANG_KEY.REFERS_TO]: 'Refers To',
  [LANG_KEY.DATE_FROM]: 'Date From',
  [LANG_KEY.DATE_TO]: 'Date To',
  [LANG_KEY.DRIVERS]: 'Drivers',
  [LANG_KEY.PHONE_NUMBER]: 'Phone Number',
  [LANG_KEY.LANGUAGE]: 'Language',
  [LANG_KEY.COMMISSION_PER_TASK]: 'Commission Per Task',
  [LANG_KEY.WORKING_REGIONS]: 'Working Regions',
  [LANG_KEY.WORKING_REGION]: 'Working Region',
  [LANG_KEY.NAME]: 'Name',
  [LANG_KEY.WORKER_NAME]: 'Worker Name',
  [LANG_KEY.CREATE_REGION]: 'Create Region',
  [LANG_KEY.PARENT_REGION]: 'Parent Region',
  [LANG_KEY.LONG_NAME]: 'Long Name',
  [LANG_KEY.SHORT_NAME]: 'Short Name',
  [LANG_KEY.ADD_APPLICATION_GROUP]: 'Add Application Group',
  [LANG_KEY.APPLICATIONS]: 'Applications',
  [LANG_KEY.SELECT_APPLICATION_GROUP_TO_LOAD_ITS_ROLES]: 'Select Application Group To Loads It\'s Roles',
  [LANG_KEY.ADD_ROLE]: 'Add Role',
  [LANG_KEY.ADD_APPLICATION]: 'Add Application',
  [LANG_KEY.SHOW_VERSIONS]: 'Show Versions',
  [LANG_KEY.SELECT_APPLICATION_TO_LOAD_ITS_VERSIONS]: 'Select Application To Load It\'s Versions',
  [LANG_KEY.ADD_COMPANY]: 'Add Company',
  [LANG_KEY.COMPANY_NAME]: 'Company Name',
  [LANG_KEY.ADMIN_USER]: 'Admin User',
  [LANG_KEY.APPLICATION_GROUP]: 'Application Group',
  [LANG_KEY.ROLE_NAME]: 'Role Name',
  [LANG_KEY.WRITE_ACCESS]: 'Write Access',
  [LANG_KEY.READ_ACCESS]: 'Read Access',
  [LANG_KEY.ADD_USER]: 'Add User',
  [LANG_KEY.ROLES]: 'Roles',
  [LANG_KEY.VERSION]: 'Versions',
  [LANG_KEY.ADD_VERSION]: 'Add Versions',
  [LANG_KEY.APPLICATION_ROLE]: 'Application Role',
  [LANG_KEY.COMPANIES]: 'Companies',
  [LANG_KEY.PARTNER_NAME]: 'Partner Name',
  [LANG_KEY.PARTNER_TYPE]: 'Partner Type',
  [LANG_KEY.DELETE_GENERAL_BILLING_RULE]: 'Delete General Billing Rule',
  [LANG_KEY.BILLING_TYPE]: 'Billing Type',
  [LANG_KEY.IS_USER_MANAGER]: 'Can User Manager',
  [LANG_KEY.APPLICATIONS_AND_VERSIONS]: 'Applications and Versions',
  [LANG_KEY.CONTROLS]: 'Controls',
  [LANG_KEY.APPLICATION_GROUPS]: 'Application Groups',
  [LANG_KEY.REPORTS]: 'Reports',
  [LANG_KEY.ADD_PARTNER_AGREEMENT]: 'Add Partner Agreement',
  [LANG_KEY.REFRESH]: 'Refresh',
  [LANG_KEY.CHOOSE_PARTNER]: 'Choose Partner',
  [LANG_KEY.BACK]: 'Back',
  [LANG_KEY.FILTER]: 'Filter',
  [LANG_KEY.SEARCH_FOR_PERSON]: 'Search For Person',
  [LANG_KEY.BY_FULL_NAME]: 'By Full Name',
  [LANG_KEY.BY_PERSONAL_ID]: 'By Personal ID',
  [LANG_KEY.ADD_NEW_PERSON]: 'Add New Person',
  [LANG_KEY.USER_CREDENTIALS]: 'User Credentails',
  [LANG_KEY.SELECT_ROLE]: 'Select Role',
  [LANG_KEY.GOOGLE_LOCATION_LINK]: 'Google Map Location Link',
  [LANG_KEY.POLICIES]: 'Policies',
  [LANG_KEY.SEARCH_BY]: 'Search By',
  [LANG_KEY.SHOW_TRANSACTION]: 'Show Transaction',
  [LANG_KEY.ADD_POLICY]: 'Add Policy',
  [LANG_KEY.CREATE_TRANSACTION]: 'Create Transaction',
  [LANG_KEY.POLICY_STATUS]: 'Policy Status',
  [LANG_KEY.ANY]: 'Any',
  [LANG_KEY.DRAFT]: 'Draft',
  [LANG_KEY.SOLD]: 'Sold',
  [LANG_KEY.EXPIRED]: 'Expired',
  [LANG_KEY.POLICY_CATEGORY]: 'Policy Category',
  [LANG_KEY.COMMISSIONS]: 'Commissions',
  [LANG_KEY.PERCENTAGE]: 'Percentage',
  [LANG_KEY.PERSON_NOT_FOUND]: 'Person Not Found',
  [LANG_KEY.CREATE_USER]: 'Create User',
  [LANG_KEY.COMPANY_TYPE]: 'Company Type',
  [LANG_KEY.BRANCHES]: 'Branches',
  [LANG_KEY.EMPLOYEES]: 'Employees',
  [LANG_KEY.ADD_BRANCH]: 'Add Branch',
  [LANG_KEY.PHONE_NUMBERS]: 'Phone Numbers',
  [LANG_KEY.EMAILS]: 'Emails',
  [LANG_KEY.ADDRESS]: 'Address',
  [LANG_KEY.BRANCH_NAME]: 'Branch Name',
  [LANG_KEY.ADD_PHONE_NUMBER]: 'Add Phone Number',
  [LANG_KEY.ADD_EMAIL]: 'Add Email',
  [LANG_KEY.COUNTRY]: 'Country',
  [LANG_KEY.CITY]: 'City',
  [LANG_KEY.QUARTER]: 'Quarter',
  [LANG_KEY.STREET]: 'Street',
  [LANG_KEY.BUILDING]: 'Building',
  [LANG_KEY.FLOOR]: 'Floor',
  [LANG_KEY.CONFIGURATION]: 'Configuration',
  [LANG_KEY.ADD_COMPANY_TYPE]: 'Add Company Type',
  [LANG_KEY.UPDATE_COMPANY]: 'Update Company',
  [LANG_KEY.SHOW_BRANCHES]: 'Show Branches',
  [LANG_KEY.JOB_TITLE]: 'Job Title',
  [LANG_KEY.ADD_EMPLOYEE]: 'Add Employee',
  [LANG_KEY.COMPANY_BRANCH]: 'Company Branch',
  [LANG_KEY.PLEASE_SELECT_AN_EMPLOYEE_TO_SEE_THE_PHONE_NUMBER_AND_HIS_EMAIL]: 'Please Select An Employee To See PhoneNumber and his Email',
  [LANG_KEY.PLEASE_SELECT_AN_BRANCH_TO_SEE_THE_PHONE_NUMBER_AND_BRANCH_EMAIL]: 'Please Select An Branch To See PhoneNumber and Branch Email',
  [LANG_KEY.COMPANY_FILTER]: 'Company Filter',
  [LANG_KEY.ALL]: 'All',
  [LANG_KEY.ADD_CURRENCY]: 'Add Currency',
  [LANG_KEY.CURRENCIES]: 'Currencies',
  [LANG_KEY.PLEASE_SELECT_APPLICATION_TO_LOAD_ITS_VERSION]: "Please Select Application To Load It's Versions",
  [LANG_KEY.PARENT_CATEGORY]: 'Parent Category',
  [LANG_KEY.CATEGORY_NAME]: 'Category Name',
  [LANG_KEY.ADD_POLICY_CATEGORY]: 'Add Policy Category',
  [LANG_KEY.POLICY_CATEGORIES]: 'Policy Categories',
  [LANG_KEY.ADD_POLICY_TRANSACTION]: 'Add Policy Transaction',
  [LANG_KEY.CREATED_AT]: 'Created At',
  [LANG_KEY.ADD_POLICY_REQUEST]: 'Add Policy Request',
  [LANG_KEY.ADD_NEW_COMMISSION]: 'Add New Commission',
  [LANG_KEY.ROLE]: 'Role',
  [LANG_KEY.CHOOSE_POLICY_CATEGORY]: 'Choose Policy Category',
  [LANG_KEY.QUANTITY]: 'Quantity',
  [LANG_KEY.FILL_THE_INFO]: 'Fill The Info',
  [LANG_KEY.POLICY_INFO]: 'Policy Info',
  [LANG_KEY.PERSON_INFO]: 'Person Info',
  [LANG_KEY.TRANSACTION_DETAILS]: 'Transaction Details',
  [LANG_KEY.PRICE_CURRENCY]: 'Price Currency',
  [LANG_KEY.COMMISSION_AGREEMENTS_PERCENTAGE]: 'Commission Agreements Persentage',
  [LANG_KEY.DISCOUNT_PERCENTAGE]: 'Discount Percentage',
  [LANG_KEY.BROKER_COMMISSION_PERCENTAGE]: 'Broker Commission Persentage',
  [LANG_KEY.PERSON_INFO_FILES]: 'Person Info Files',
  [LANG_KEY.POLICY_INFO_FILES]: 'Policy Info Files',
  [LANG_KEY.DRAG_AND_DROP_ANY_IMAGE]: 'Drag and Drop Any File',
  [LANG_KEY.UPLOAD_FILES]: 'Upload Files',
  [LANG_KEY.NO_PHONE_NUMBERS_ARE_FOUND]: 'No Phones Numbers are Found',
  [LANG_KEY.NO_EMAIL_ADDRESSES_ARE_FOUND]: 'No Emails Addresses are Found',
  [LANG_KEY.INCURANCE_COMPANY]: 'Incurance Company',
  [LANG_KEY.COMMISION_AGREEMENT]: 'Commision Agreement',
  [LANG_KEY.PRICE]: 'Price',
  [LANG_KEY.BROKER_COMMISION_AGREEMENT]: 'Broker Commision Agreement',
  [LANG_KEY.FILES]: 'Files',
  [LANG_KEY.BIRTHDATE]: 'BirthDate',
  [LANG_KEY.PHONES]: 'Phone',
  [LANG_KEY.CLICK_ON_THE_IMAGE_TO_DOWNLOAD]: 'Click on The Image to Download',
  [LANG_KEY.INVOICE_TYPES]: 'Invoice Types',
  [LANG_KEY.PLEASE_SELECT_COMPANY_TO_VIEW_IT_TYPE_AND_APPLICATION_ROLE]: 'Please Select Company To View It Types and Application group',
  [LANG_KEY.VERSIONS]: 'Versions',
  [LANG_KEY.PHONES_EMAILS]: 'Phones & Emails',
  [LANG_KEY.COST_INFO]: 'Cost Info',
  [LANG_KEY.AGREEMENT_START_DATE]: 'Agreement Start Date',
  [LANG_KEY.AGREEMENT_END_DATE]: 'Agreement End Date',
  [LANG_KEY.CONFIRMS]: 'Confirms',
  [LANG_KEY.ARE_YOY_SURE_YOU_WANT_TO_DELETE]: 'Are you Sure You Want To Delete ?',
  [LANG_KEY.BILLING_AND_PAYMENTS]: 'Billing and Payments',
  [LANG_KEY.PAYER_NAME]: 'Payer Name',
  [LANG_KEY.RECEIVER_NAME]: 'Receiver Name',
  [LANG_KEY.CREATOR_NAME]: 'Creator Name',
  [LANG_KEY.TOTAL_AMOUNT]: 'Total Amount',
  [LANG_KEY.SEARCH] : 'Search',
  [LANG_KEY.CLEAR] : 'Clear',
  [LANG_KEY.ADD_PAYMENT]: 'Add Payment',
  [LANG_KEY.PAYMENT_METHOD]: 'Payment Method',
  [LANG_KEY.REFERENCE_NUMBER]: 'Reference Number',
  [LANG_KEY.AMOUNT]: 'Amount',
  [LANG_KEY.CURRENCY]: 'Currency',
  [LANG_KEY.DUE_DATE]: 'Due Date',
  [LANG_KEY.ACTUAL_DATE]: 'Actual Date',
  [LANG_KEY.STATUS]: 'Status',
  [LANG_KEY.CHEQUE]: 'Cheque',
  [LANG_KEY.CASH]: 'Cash',
  [LANG_KEY.DEFUALT_CURRENCY]: 'Defualt Currency',
  [LANG_KEY.BILLING]: 'Billing',
  [LANG_KEY.ADD_FIELD]: 'Add Field',
  [LANG_KEY.FIXED_FEES_PER_AGREEMENTS]: 'Fixed Fees Per Agreement',
  [LANG_KEY.AGREEMENT_FEES]: 'Agreement Fees',
  [LANG_KEY.TRANSACTION_COMMISSION_FEES]: 'Transaction Commission Fees',
  [LANG_KEY.TRASNSACTION_FEES]: 'Transaction Fees',
  [LANG_KEY.PLATE_SYMBOL]: 'Plate Symbol',
  [LANG_KEY.FREE_LANCER_TODRIVER]: 'Free Lancer TowDriver',
  [LANG_KEY.APPLICATION_TYPE]: 'Application Type',
  [LANG_KEY.MOBILE_APP]: 'Mobile app',
  [LANG_KEY.WEB_APP]: 'Web app',
  [LANG_KEY.APPLICATION_URL]: 'Application Url',
  [LANG_KEY.UPLOAD_LOGO]: 'Upload Logo',
  [LANG_KEY.REQUEST_INFORMATION]: 'Request Info',
  [LANG_KEY.REQUEST_FIELDS]: 'Request Fields',
  [LANG_KEY.HAS_BROKER]: 'Using Broker',
  [LANG_KEY.POLICY_START_DATE]: 'Policy Start Date',
  [LANG_KEY.POLICY_END_DATE]: 'Policy End Date',
  [LANG_KEY.CHOOSE_COMPANIES]: 'Choose Companies',
  [LANG_KEY.FIXED_FEES_CURRENCY]: 'Fixed Fees Currency',
  [LANG_KEY.ACCIDENT_FEES_CURRENCY]: 'Accident Fees Currency',
  [LANG_KEY.MECHANICAL_SERVICE_FEES_CURRENCY]: 'Mechanical Service Fees Currency',
  [LANG_KEY.VACATION_FEES_CURRENCY]: 'Vacation Fees Currency',
  [LANG_KEY.VEHICLE_PRIVATE_FEES_CURRENCY]: 'Vehicle Private Fees Currency',
  [LANG_KEY.VEHICLE_TYPE_FEES_CURRENCY]: 'Vehicle Type Fees Currency',
  [LANG_KEY.LATE_NIGHT_FEES_CURRENCY]: 'Late Night Fees Currency',
  [LANG_KEY.MINIMUM_FEES_CURRENCY]: 'Minimum Fees Currency',
  [LANG_KEY.FEES_PER_KM_CURRENCY]: 'Fees Per KM Currency',
  [LANG_KEY.EASY_ROAD_FEES_CURRENCY]: 'Easy Road Fees Currency',
  [LANG_KEY.MEDIUM_ROAD_FEES_CURRENCY]: 'Medium Road Fees Currency',
  [LANG_KEY.DIFFICULT_ROAD_FEES_CURRENCY]: 'Difficult Road Fees Currency',
  [LANG_KEY.ACCEPT]: 'Accept',
  [LANG_KEY.ACCEPTED]: 'Accepted',
  [LANG_KEY.ESTIMATED_FEES_CURRENCY]: 'Estimated Fees Currency',
  [LANG_KEY.ADDITIONAL_COST_CURRENCY]: 'Additional Fees Currency',
  [LANG_KEY.POLICY_TRANSACTION_FEES]: 'Policy Transaction Fees',
  [LANG_KEY.POLICY_TRANSACTION_COMMISSION]: 'Policy Transaction Commission',
  [LANG_KEY.POLICY_TRANSACTION_BROKER_COMMISSION]: 'Policy Transaction Broker Commission',  
  [LANG_KEY.FORBIDDEN]: '403 Forbidden',
  [LANG_KEY.YOU_HAVE_NO_ACCESS_ON_THIS_PAGE]: 'You Have No Access On This Page',
  [LANG_KEY.BACK_TO_HOME_PAGE]: 'Back To Home Page',
  [LANG_KEY.USERS_PROFILE]: 'Users Profile',
  [LANG_KEY.ADD_COMPANY_EMAIL]: 'Add Company Email',
  [LANG_KEY.EMAIL]: 'Email',
  [LANG_KEY.COMPANIES_EMAIL]: 'Companies Email',
  [LANG_KEY.BIILING_RULE]: 'Billing Rule',
  [LANG_KEY.CANCELED]: 'Canceled',
  [LANG_KEY.ACTIVE]: 'Active',
  [LANG_KEY.SELECT]: 'Select',
  [LANG_KEY.MONEY_CONVERSION]: 'Money Conversion',
  [LANG_KEY.ADD_MONEY_CONVERSION]: 'Add Money Conversion',
  [LANG_KEY.FROM]: 'From',
  [LANG_KEY.TO]: 'To',
  [LANG_KEY.RATE]: 'Rate',
  [LANG_KEY.FROM_CURRENCY]: 'From Currency',
  [LANG_KEY.TO_CURRENCY]: 'To Currency',
  [LANG_KEY.WEBSITE]: 'Website',
  [LANG_KEY.IS_DEFAULT]: 'Is Default',
  [LANG_KEY.NO]: "No",
  [LANG_KEY.PLEASE_SELECT_CONTACT_TO_SHOW_DETAILS]: 'Please select contact to show details',
  [LANG_KEY.ADD_NEW_CONTACT]: 'Add New Contact',
  [LANG_KEY.SEARCH_BY_NAME]: 'Search By Name',
  [LANG_KEY.COMPANY_MAIN_EMAIL]: 'Company Main Email',
  [LANG_KEY.MAIN_EMAIL]: 'Main Email',
  [LANG_KEY.ADD_BRAND]: 'Add Brand',
  [LANG_KEY.PLEASE_SELECT_BRAND_TO_SHOW_ITS_MODELS]: 'Please select brand to show its models',
  [LANG_KEY.VEHICLES]: 'Vehicles',
  [LANG_KEY.ADD_MODEL]: 'Add Model',
  [LANG_KEY.MODEL]: 'Model',
  [LANG_KEY.ADD_SECONDARY_EMAIL]: 'Add Secondary Email',
  [LANG_KEY.PLEASE_SELECT_COMPANY_T0_VIEW_SECONDARY_EMAILS]: 'Please Select Company To View Secondary Email',
  [LANG_KEY.SHOW_EMAILS]: 'Show Email',
  [LANG_KEY.INSURANCE_CATEGORY]: 'Insurance Category'
};
