import { LANG_KEY } from './lang-keys';

// lang-ar.ts
export const LANG_AR_NAME = 'ar';

export const LANG_AR_TRANS: { [key in LANG_KEY]?: string } = {
  [LANG_KEY.CREATE]: 'خلق',
  [LANG_KEY.CREATE_PROFESSION]: 'خلق مهنة',
  [LANG_KEY.NAME]: 'اسم',
  [LANG_KEY.FILTER_BY_NAME]: 'تصفية حسب الاسم',
  [LANG_KEY.UPDATE]: 'تحديث',
  [LANG_KEY.DELETE]: 'حذف',
  [LANG_KEY.SUBMIT]: 'إرسال',
  [LANG_KEY.USERNAME]: 'اسم المستخدم',
  [LANG_KEY.PASSWORD]: 'كلمه السر',
  [LANG_KEY.LOGOUT]: 'تسجيل خروج',
  [LANG_KEY.WORKERS]: 'عمال',
  [LANG_KEY.PROFESSIONS]: 'المهن',
  [LANG_KEY.TRANSACTIONS]: 'المعاملات',
  [LANG_KEY.FILTER_BY]: 'مصنف بواسطة',
  [LANG_KEY.REQUESTS]: 'الطلبات',
  [LANG_KEY.CUSTOMER_LOCATION]: 'موقع العميل',
  [LANG_KEY.CUSTOMER_NAME]: 'اسم الزبون',
  [LANG_KEY.PROFESSION]: 'مهنة',
  [LANG_KEY.DESCRIPTION]: 'وصف',
  [LANG_KEY.DATE]: 'تاريخ',
  [LANG_KEY.CREATE_WORKER]: 'إنشاء عامل',
  [LANG_KEY.USERS]: 'المستخدمون',
  [LANG_KEY.FIRST_NAME]: 'الاسم الاول',
  [LANG_KEY.MIDDEL_NAME]: 'الاسم الوسطى',
  [LANG_KEY.LAST_NAME]: 'الكنية',
  [LANG_KEY.MOTHER_NAME]: 'اسم الأم',
  [LANG_KEY.BLOOD_TYPE]: 'فصيلة الدم',
  [LANG_KEY.PERSONAL_ID]: 'رقم الهوية الشخصية',
  [LANG_KEY.DATE_OF_BIRTH]: 'تاريخ الولادة',
  [LANG_KEY.PROFESSION_NAME]: 'اسم المهنة',
  [LANG_KEY.LOGIN]: 'تسجيل الدخول',
  [LANG_KEY.PLATE_NUMBER]: 'رقم لوحة',
  [LANG_KEY.CHECK]: 'التحقق',
  [LANG_KEY.N0_VEHICLE_FOUND_CREATE_ONE]: 'لم يتم العثور على مركبة قم بإنشاء واحدة',
  [LANG_KEY.CREATE_NEW_VEHICLE]: 'إنشاء مركبة جديدة',
  [LANG_KEY.VEHICLE_INFO]: 'معلومات السيارة',
  [LANG_KEY.VEHICLE_NAME]: 'اسم المركبة',
  [LANG_KEY.TYPE]: 'نوع',
  [LANG_KEY.NUMBER_OF_SEATS]: 'عدد المقاعد',
  [LANG_KEY.WEIGHT]: 'وزن',
  [LANG_KEY.DETAILS]: 'تفاصيل',
  [LANG_KEY.NEXT]: 'التالى',
  [LANG_KEY.ADD_NEW_VEHICLE]: 'إضافة مركبة جديدة',
  [LANG_KEY.CUSTOMER]: 'الزبون',
  [LANG_KEY.CREATE_NEW_PERSON]: 'إنشاء شخص جديد',
  [LANG_KEY.CUSTOMER_INFO]: 'معلومات العميل',
  [LANG_KEY.FULL_NAME]: 'الاسم الكامل',
  [LANG_KEY.ADD_NEW_CUSTOMER]: 'إضافة عميل جديد',
  [LANG_KEY.SOURCE]: 'مصدر',
  [LANG_KEY.DESTINATION]: 'المكان المقصود',
  [LANG_KEY.TOWING_TICKET_DETAILS]: 'تفاصيل تذكرة القطر',
  [LANG_KEY.ESTIMATED_TIME]: 'الوقت المقدر',
  [LANG_KEY.ID]: 'ID',
  [LANG_KEY.ROAD_TYPE]: 'نوع الطريق',
  [LANG_KEY.DATE_TIME]: 'التاريخ والوقت',
  [LANG_KEY.SOURCE_NAME]: 'اسم المصدر',
  [LANG_KEY.DESTINATION_NAME]: 'اسم الوجهة',
  [LANG_KEY.SHOW_DETAILS]: 'اظهر التفاصيل',
  [LANG_KEY.ADD_REQUEST]: 'أضف طلب',
  [LANG_KEY.IMPORT_USER_POLICIES]: 'استيراد سياسات المستخدم',
  [LANG_KEY.ADD_AGREEMENT]: 'إضافة اتفاقية',
  [LANG_KEY.COMPANY]: 'شركة',
  [LANG_KEY.BILLING_TYPE]: 'نوع الفاتورة',
  [LANG_KEY.MAX_TRANSACTION_PER_DAY]: 'الحد الأقصى للمعاملة في اليوم',
  [LANG_KEY.MAX_KM_BY_TRANSACTION]: 'الحد الأقصى للكيلومتر لكل معاملة',
  [LANG_KEY.MECHANICAL_SERVICE_FEES]: 'رسوم الخدمة الميكانيكية',
  [LANG_KEY.ACCIDENT_SERVICE_FEES]: 'رسوم خدمة الحوادث',
  [LANG_KEY.EDIT]: 'تعديل',
  [LANG_KEY.AGREEMENT_TYPE]: 'نوع الاتفاقية',
  [LANG_KEY.TOTAL_DISTANCE]: 'المسافة الكلية',
  [LANG_KEY.TOTAL_COST]: 'التكلفة الإجمالية',
  [LANG_KEY.INSURANCE_COMPANY]: 'شركة تأمين',
  [LANG_KEY.CREATE_TOWDRIVER]: 'إنشاء سائق',
  [LANG_KEY.INSURANCE_AGREEMENTS]: 'اتفاقيات التأمين',
  [LANG_KEY.TOWING_PARTNERS_AGREEMENTS]: 'اتفاقيات الشركاء',
  [LANG_KEY.BILLING_CONFIGURATION]: 'تحرير الفواتير',
  [LANG_KEY.REPORTING]: 'إعداد التقارير',
  [LANG_KEY.SELECT_COMPANY]: 'حدد الشركة',
  [LANG_KEY.PAYMENT_TYPE]: 'نوع الدفع',
  [LANG_KEY.POSTPAID_MODE]: 'وضع الدفع المؤخر',
  [LANG_KEY.PREPAID]: 'مسبقة الدفع',
  [LANG_KEY.POSTPAID]: 'الدفع المؤجل',
  [LANG_KEY.FIXED]: 'ثابت',
  [LANG_KEY.DYNAMIC]: 'ديناميكي',
  [LANG_KEY.FIXED_FEES_PER_POLICY]: 'رسوم ثابتة لكل سياسة',
  [LANG_KEY.FIXED_FEES_PER_TRANSACTION]: 'رسوم ثابتة لكل معاملة',
  [LANG_KEY.UNLIMITED]: 'غير محدود',
  [LANG_KEY.MAX_ALLOWED_TRANSACTIONS_PER_DAY]: 'الحد الأقصى المسموح به للمعاملة في اليوم الواحد',
  [LANG_KEY.MAX_ALLOWED_TRANSACTIONS_PER_YEAR]: 'الحد الأقصى المسموح به للمعاملة في السنة',
  [LANG_KEY.MAX_KM_TRANSACTION]: 'الحد الأقصى للكيلومتر حسب المعاملة',
  [LANG_KEY.MECHANICAL_SERVICE_TYPE_FEES]: 'رسوم نوع الخدمة الميكانيكية',
  [LANG_KEY.ACCIDENT_SERVICE_TYPE_FEES]: 'رسوم نوع خدمة الحوادث',
  [LANG_KEY.SAVE]: 'حفظ',
  [LANG_KEY.CATEGORIES]: 'التصنيفات',
  [LANG_KEY.MINIMUM_TRANSACTION_FEES]: 'رسوم المعاملات الدنيا',
  [LANG_KEY.FEES_PER_KM]: 'الرسوم لكل كم',
  [LANG_KEY.MAXIMUM_COVERED_DISTANCE]: 'أقصى مسافة مغطاة',
  [LANG_KEY.EASY_ROAD_NAVIGATION_FEES]: 'رسوم سهلة للملاحة على الطرق',
  [LANG_KEY.MEDIUM_ROAD_NAVIGATION_FEES]: 'رسوم الملاحة على الطرق المتوسطة',
  [LANG_KEY.DIFFICULT_ROAD_NAVIGATION_FEES]: 'رسوم الملاحة على الطرق الصعبة',
  [LANG_KEY.ADD]: 'أضف',
  [LANG_KEY.LATE_NIGHT_TRANSACTION_FEES]: 'رسوم المعاملات في وقت متأخر من الليل',
  [LANG_KEY.VEHICLE_OVER_M_TYPE_FEES]: 'رسوم مركبة فوق سطح السيارة',
  [LANG_KEY.VEHICLE_PRIVATE_TYPE_FEES]: 'رسوم المركبة الخاصة',
  [LANG_KEY.VACATION_TRANSACTION_FEES]: 'رسوم معاملات الإجازة',
  [LANG_KEY.ADD_SPECIFIC_BILLING_RULE]: 'إضافة قاعدة فوترة محددة',
  [LANG_KEY.CATEGORY]: 'الفئة',
  [LANG_KEY.TRANSACTION_FEES]: 'رسوم التحويل',
  [LANG_KEY.MAXIMUM_DISTANCE]: 'المسافة القصوى',
  [LANG_KEY.EASY_ROAD]: 'طريق سهل',
  [LANG_KEY.MEDIUM_ROAD]: 'طريق متوسط',
  [LANG_KEY.DIFFICULT_ROAD]: 'طريق صعب',
  [LANG_KEY.VEHICLE_MODEL]: 'موديل المركبة',
  [LANG_KEY.VEHICLE_BRAND]: 'ماركة السيارة',
  [LANG_KEY.VEHICLE_TYPE]: 'نوع السيارة',
  [LANG_KEY.VEHICLE_DETAILS]: 'تفاصيل السيارة',
  [LANG_KEY.VEHICLE]: 'مركبة',
  [LANG_KEY.PARTY_TYPE]: 'نوع الحفلة',
  [LANG_KEY.PERSON]: 'شخص',
  [LANG_KEY.TOW_DRIVER_RESPONSE]: 'استجابة السائق',
  [LANG_KEY.SEND_BROADCAST]: 'إرسال بث',
  [LANG_KEY.COMPANY_DRIVERS]: 'سائقو الشركة',
  [LANG_KEY.FREELANCE_DRIVERS]: 'سائقين لحسابهم الخاص',
  [LANG_KEY.PARTNERS_DRIVERS]: 'السائقين الشركاء',
  [LANG_KEY.ARE_YOU_SURE_YOU_WANT_TO_LOCK_THIS_RWQUEST_TO]: 'هل أنت متأكد أنك تريد قفل هذا الطلب',
  [LANG_KEY.CANCEL]: 'إلغاء',
  [LANG_KEY.YES]: 'نعم',
  [LANG_KEY.TICKET_INFO]: 'معلومات التذكرة',
  [LANG_KEY.WHEEL_STATUS]: 'حالة العجلة',
  [LANG_KEY.ADD_TICKET]: 'أضف تذكرة',
  [LANG_KEY.ROAD_ENVIRONMENT]: 'بيئة الطريق',
  [LANG_KEY.EASY]: 'سهل',
  [LANG_KEY.MEDIUM]: 'متوسط',
  [LANG_KEY.DIFFICULT]: 'صعب',
  [LANG_KEY.VACTION]: 'عطلة',
  [LANG_KEY.LATE_NIGHT]: 'وقت متأخر من الليل',
  [LANG_KEY.ESTIMATED_FEES]: 'الرسوم التقديرية',
  [LANG_KEY.DISCOUNT]: 'خصم',
  [LANG_KEY.ADDITIONAL_COST]: 'تكلفة إضافية',
  [LANG_KEY.VEHICLE_ON_WHEEL]: 'السيارة على عجلات',
  [LANG_KEY.IMPORT]: 'استيراد',
  [LANG_KEY.END_DATE]: 'تاريخ الانتهاء',
  [LANG_KEY.START_DATE]: 'تاريخ البدء',
  [LANG_KEY.CAR_CATEGORY]: 'فئة السيارة',
  [LANG_KEY.POLICY_TYPE]: 'نوع السياسة',
  [LANG_KEY.POLICY_NUMBER]: 'رقم مركز الشرطه',
  [LANG_KEY.USER_POLICIES]: 'سياسات المستخدم',
  [LANG_KEY.SELECT_FILE]: 'حدد ملف',
  [LANG_KEY.EXCEL_FIELDS]: 'حقول Excel',
  [LANG_KEY.TOWING_POLICIES_COLUMN]: 'سياسات قطر',
  [LANG_KEY.REFERS_TO]: 'يعود الى',
  [LANG_KEY.DATE_FROM]: 'من التاريخ',
  [LANG_KEY.DATE_TO]: 'حتى تاريخه',
  [LANG_KEY.DRIVERS]: 'السائقين',
  [LANG_KEY.PHONE_NUMBER]: 'رقم الهاتف',
  [LANG_KEY.LANGUAGE]: 'لغة',
  [LANG_KEY.COMMISSION_PER_TASK]: 'عمولة لكل مهمة',
  [LANG_KEY.WORKING_REGIONS]: 'مناطق العمل',
  [LANG_KEY.WORKING_REGION]: 'مناطق العمل',
  [LANG_KEY.NAME]: 'اسم',
  [LANG_KEY.WORKER_NAME]: 'اسم العامل',
  [LANG_KEY.CREATE_REGION]: 'إنشاء منطقة عمل',
  [LANG_KEY.PARENT_REGION]: 'المنطقة الأم',
  [LANG_KEY.LONG_NAME]: 'اسم',
  [LANG_KEY.SHORT_NAME]: 'اسم قصير',
  [LANG_KEY.ADD_APPLICATION_GROUP]: 'أضف مجموعة التطبيقات',
  [LANG_KEY.APPLICATIONS]: 'التطبيقات',
  [LANG_KEY.SELECT_APPLICATION_GROUP_TO_LOAD_ITS_ROLES]: 'حدد مجموعة التطبيقات لتحميل أدوارها',
  [LANG_KEY.ADD_ROLE]: 'إضافة دور',
  [LANG_KEY.ADD_APPLICATION]: 'إضافة تطبيق',
  [LANG_KEY.SHOW_VERSIONS]: 'إظهار الإصدارات',
  [LANG_KEY.SELECT_APPLICATION_TO_LOAD_ITS_VERSIONS]: 'حدد التطبيق لتحميل إصداراته',
  [LANG_KEY.ADD_COMPANY]: 'أضف شركة',
  [LANG_KEY.COMPANY_NAME]: 'اسم الشركة',
  [LANG_KEY.ADMIN_USER]: 'المستخدم المسؤول',
  [LANG_KEY.APPLICATION_GROUP]: 'مجموعة التطبيق',
  [LANG_KEY.ROLE_NAME]: 'اسم الدور',
  [LANG_KEY.WRITE_ACCESS]: 'كتابة الوصول',
  [LANG_KEY.READ_ACCESS]: 'قراءة الوصول',
  [LANG_KEY.ADD_USER]: 'أضف مستخدم',
  [LANG_KEY.ROLES]: 'الأدوار',
  [LANG_KEY.VERSION]: 'إصدارات',
  [LANG_KEY.ADD_VERSION]: 'أضف إصدارات',
  [LANG_KEY.APPLICATION_ROLE]: 'دور التطبيق',
  [LANG_KEY.COMPANIES]: 'الشركات',
  [LANG_KEY.PARTNER_NAME]: 'اسم شريك',
  [LANG_KEY.PARTNER_TYPE]: 'نوع الشريك',
  [LANG_KEY.DELETE_GENERAL_BILLING_RULE]: 'حذف قاعدة عامة للفواتير',
  [LANG_KEY.BILLING_TYPE]: 'نوع الفاتورة',
  [LANG_KEY.IS_USER_MANAGER]: 'يمكن إدارة المستخدمين',
  [LANG_KEY.APPLICATIONS_AND_VERSIONS]: 'التطبيقات والإصدارات',
  [LANG_KEY.CONTROLS]: 'ضوابط',
  [LANG_KEY.APPLICATION_GROUPS]: 'مجموعات التطبيقات',
  [LANG_KEY.REPORTS]: 'التقارير',
  [LANG_KEY.ADD_PARTNER_AGREEMENT]: 'إضافة اتفاقية شريك',
  [LANG_KEY.REFRESH]: 'تحديث',
  [LANG_KEY.CHOOSE_PARTNER]: 'اختر شريك',
  [LANG_KEY.BACK]: 'عودة',
  [LANG_KEY.FILTER]: 'بحث',
  [LANG_KEY.SEARCH_FOR_PERSON]: 'ابحث عن شخص',
  [LANG_KEY.BY_FULL_NAME]: 'بالاسم الكامل',
  [LANG_KEY.BY_PERSONAL_ID]: 'عن طريق الهوية الشخصية',
  [LANG_KEY.ADD_NEW_PERSON]: 'إضافة شخص جديد',
  [LANG_KEY.USER_CREDENTIALS]: 'بيانات اعتماد المستخدم',
  [LANG_KEY.SELECT_ROLE]: 'حدد الدور',
  [LANG_KEY.GOOGLE_LOCATION_LINK]: 'رابط موقع خريطة جوجل',
  [LANG_KEY.POLICIES]: 'بوالص',
  [LANG_KEY.SEARCH_BY]: 'البحث عن طريق',
  [LANG_KEY.SHOW_TRANSACTION]: 'إظهار المعاملة',
  [LANG_KEY.ADD_POLICY]: 'أضف سياسة',
  [LANG_KEY.CREATE_TRANSACTION]: 'إنشاء معاملة',
  [LANG_KEY.POLICY_STATUS]: 'حالة السياسة',
  [LANG_KEY.ANY]: 'الكل',
  [LANG_KEY.DRAFT]: 'مشروع',
  [LANG_KEY.SOLD]: 'تم البيع',
  [LANG_KEY.EXPIRED]: 'منتهية الصلاحية',
  [LANG_KEY.POLICY_CATEGORY]: 'فئة السياسة',
  [LANG_KEY.COMMISSIONS]: 'عمولة',
  [LANG_KEY.PERCENTAGE]: 'النسبة المئوية',
  [LANG_KEY.PERSON_NOT_FOUND]: 'لم يتم العثور على الشخص',
  [LANG_KEY.CREATE_USER]: 'إنشاء مستخدم',
  [LANG_KEY.COMPANY_TYPE]: 'إنشاء نوع',
  [LANG_KEY.BRANCHES]: 'الفروع',
  [LANG_KEY.EMPLOYEES]: 'الموظفين',
  [LANG_KEY.ADD_BRANCH]: 'إضافة فرع',
  [LANG_KEY.PHONE_NUMBERS]: 'أرقام الهواتف',
  [LANG_KEY.EMAILS]: 'رسائل البريد الإلكتروني',
  [LANG_KEY.ADDRESS]: 'عنوان',
  [LANG_KEY.BRANCH_NAME]: 'اسم الفرع',
  [LANG_KEY.ADD_PHONE_NUMBER]: 'أضف رقم الهاتف',
  [LANG_KEY.ADD_EMAIL]: 'أضف بريدًا إلكترونيًا',
  [LANG_KEY.COUNTRY]: 'بلد',
  [LANG_KEY.CITY]: 'مدينة',
  [LANG_KEY.QUARTER]: 'ربع',
  [LANG_KEY.STREET]: 'شارع',
  [LANG_KEY.BUILDING]: 'بناء',
  [LANG_KEY.FLOOR]: 'أرضية',
  [LANG_KEY.CONFIGURATION]: 'ترتيب',
  [LANG_KEY.ADD_COMPANY_TYPE]: 'أضف نوع الشركة',
  [LANG_KEY.UPDATE_COMPANY]: 'تحديث الشركة',
  [LANG_KEY.SHOW_BRANCHES]: 'إظهار الفروع',
  [LANG_KEY.JOB_TITLE]: 'عنوان وظيفي',
  [LANG_KEY.ADD_EMPLOYEE]: 'إضافة موظف',
  [LANG_KEY.COMPANY_BRANCH]: 'فرع شركة',
  [LANG_KEY.PLEASE_SELECT_AN_EMPLOYEE_TO_SEE_THE_PHONE_NUMBER_AND_HIS_EMAIL]: 'يرجى تحديد موظف لرؤية رقم الهاتف والبريد الإلكتروني الخاص به',
  [LANG_KEY.PLEASE_SELECT_AN_BRANCH_TO_SEE_THE_PHONE_NUMBER_AND_BRANCH_EMAIL]: 'يرجى تحديد فرع لرؤية رقم الهاتف والبريد الإلكتروني للفرع',
  [LANG_KEY.COMPANY_FILTER]: 'تصفية الشركة',
  [LANG_KEY.ALL]: 'الكل',
  [LANG_KEY.ADD_CURRENCY]: 'أضف عملة',
  [LANG_KEY.CURRENCIES]: 'العملات',
  [LANG_KEY.PLEASE_SELECT_APPLICATION_TO_LOAD_ITS_VERSION]: "يرجى تحديد التطبيق لتحميل إصداراته",
  [LANG_KEY.PARENT_CATEGORY]: 'القسم الرئيسي',
  [LANG_KEY.CATEGORY_NAME]: 'اسم التصنيف',
  [LANG_KEY.ADD_POLICY_CATEGORY]: 'إضافة فئة سياسة',
  [LANG_KEY.POLICY_CATEGORIES]: 'فئات السياسة',
  [LANG_KEY.ADD_POLICY_TRANSACTION]: 'أضف معاملة السياسة',
  [LANG_KEY.CREATED_AT]: 'أنشئت في',
  [LANG_KEY.ADD_POLICY_REQUEST]: 'إضافة طلب سياسة',
  [LANG_KEY.ADD_NEW_COMMISSION]: 'إضافة عمولة جديدة',
  [LANG_KEY.ROLE]: 'وظيفة',
  [LANG_KEY.CHOOSE_POLICY_CATEGORY]: 'اختر فئة السياسة',
  [LANG_KEY.QUANTITY]: 'كمية',
  [LANG_KEY.FILL_THE_INFO]: 'املأ المعلومات',
  [LANG_KEY.POLICY_INFO]: 'معلومات السياسة',
  [LANG_KEY.PERSON_INFO]: 'معلومات الشخص',
  [LANG_KEY.TRANSACTION_DETAILS]: 'تفاصيل الصفقه',
  [LANG_KEY.PRICE_CURRENCY]: 'عملة السعر',
  [LANG_KEY.COMMISSION_AGREEMENTS_PERCENTAGE]: 'ثبات اتفاقيات العمولة',
  [LANG_KEY.DISCOUNT_PERCENTAGE]: 'نسبة الخصم',
  [LANG_KEY.BROKER_COMMISSION_PERCENTAGE]: 'نسبة عمولة الوسيط',
  [LANG_KEY.PERSON_INFO_FILES]: 'ملفات معلومات الشخص',
  [LANG_KEY.POLICY_INFO_FILES]: 'ملفات معلومات السياسة',
  [LANG_KEY.DRAG_AND_DROP_ANY_IMAGE]: 'اسحب وأفلت أي ملف',
  [LANG_KEY.UPLOAD_FILES]: 'تحميل الملفات',
  [LANG_KEY.NO_PHONE_NUMBERS_ARE_FOUND]: 'لم يتم العثور على أرقام هواتف',
  [LANG_KEY.NO_EMAIL_ADDRESSES_ARE_FOUND]: 'لم يتم العثور على عناوين بريد إلكتروني',
  [LANG_KEY.INCURANCE_COMPANY]: 'شركة التأمين',
  [LANG_KEY.COMMISION_AGREEMENT]: 'اتفاقية العمولة',
  [LANG_KEY.PRICE]: 'السعر',
  [LANG_KEY.BROKER_COMMISION_AGREEMENT]: 'اتفاقية عمولة الوسيط',
  [LANG_KEY.FILES]: 'الملفات',
  [LANG_KEY.BIRTHDATE]: 'تاريخ الميلاد',
  [LANG_KEY.PHONES]: 'هاتف',
  [LANG_KEY.CLICK_ON_THE_IMAGE_TO_DOWNLOAD]: 'اضغط على الصورة للتحميل',
  [LANG_KEY.INVOICE_TYPES]: 'أنواع الفواتير',
  [LANG_KEY.PLEASE_SELECT_COMPANY_TO_VIEW_IT_TYPE_AND_APPLICATION_ROLE]: 'الرجاء تحديد الشركة لعرضها وأنواعها ومجموعة التطبيقات',
  [LANG_KEY.VERSIONS]: 'إصدارات',
  [LANG_KEY.PHONES_EMAILS]: 'الهواتف و البريد الإلكتروني',
  [LANG_KEY.COST_INFO]: 'معلومات التكلفة',
  [LANG_KEY.AGREEMENT_START_DATE]: 'تاريخ بدء الاتفاقية',
  [LANG_KEY.AGREEMENT_END_DATE]: 'تاريخ انتهاء الاتفاقية',
  [LANG_KEY.CONFIRMS]: 'يؤكد',
  [LANG_KEY.ARE_YOY_SURE_YOU_WANT_TO_DELETE]: 'هل أنت متأكد أنك تريد حذف ؟',
  [LANG_KEY.BILLING_AND_PAYMENTS]: 'الفواتير والمدفوعات',
  [LANG_KEY.PAYER_NAME]: 'اسم الدافع',
  [LANG_KEY.RECEIVER_NAME]: 'اسم المستلم',
  [LANG_KEY.CREATOR_NAME]: 'اسم المنشئ',
  [LANG_KEY.TOTAL_AMOUNT]: 'المبلغ الإجمالي',
  [LANG_KEY.SEARCH]: 'بحث',
  [LANG_KEY.CLEAR]: 'مسح المرشحات',
  [LANG_KEY.ADD_PAYMENT]: 'أضف الدفع',
  [LANG_KEY.PAYMENT_METHOD]: 'طريقة الدفع او السداد',
  [LANG_KEY.REFERENCE_NUMBER]: 'رقم المرجع',
  [LANG_KEY.AMOUNT]: 'كمية',
  [LANG_KEY.CURRENCY]: 'عملة',
  [LANG_KEY.DUE_DATE]: 'تاريخ الاستحقاق',
  [LANG_KEY.ACTUAL_DATE]: 'التاريخ الفعلي',
  [LANG_KEY.STATUS]: 'الحالة',
  [LANG_KEY.CHEQUE]: 'شيك',
  [LANG_KEY.CASH]: 'نقد',
  [LANG_KEY.DEFUALT_CURRENCY]: 'العملة الافتراضية',
  [LANG_KEY.BILLING]: 'الفواتير',
  [LANG_KEY.ADD_FIELD]: 'إضافة حقل',
  [LANG_KEY.FIXED_FEES_PER_AGREEMENTS]: 'رسوم ثابتة لكل اتفاقية',
  [LANG_KEY.AGREEMENT_FEES]: 'رسوم الاتفاقية',
  [LANG_KEY.TRANSACTION_COMMISSION_FEES]: 'رسوم عمولة المعاملات',
  [LANG_KEY.TRASNSACTION_FEES]: 'رسوم التحويل',
  [LANG_KEY.PLATE_SYMBOL]: 'رمز اللوحة',
  [LANG_KEY.FREE_LANCER_TODRIVER]: 'سائق سحب لحسابهم الخاص',
  [LANG_KEY.APPLICATION_TYPE]: 'نوع التطبيق',
  [LANG_KEY.MOBILE_APP]: 'تطبيق جوال',
  [LANG_KEY.WEB_APP]: 'التطبيق على شبكة الإنترنت',
  [LANG_KEY.APPLICATION_URL]: 'عنوان التطبيق',
  [LANG_KEY.UPLOAD_LOGO]: 'تحميل الشعار',
  [LANG_KEY.REQUEST_INFORMATION]: 'معلومات الطلب',
  [LANG_KEY.REQUEST_FIELDS]: 'طلب الحقول',
  [LANG_KEY.HAS_BROKER]: 'باستخدام وسيط',
  [LANG_KEY.POLICY_START_DATE]: 'تاريخ بدء السياسة',
  [LANG_KEY.POLICY_END_DATE]: 'تاريخ انتهاء السياسة',
  [LANG_KEY.CHOOSE_COMPANIES]: 'اختر الشركات',
  [LANG_KEY.FIXED_FEES_CURRENCY]: 'عملة الرسوم الثابتة',
  [LANG_KEY.ACCIDENT_FEES_CURRENCY]: 'عملة رسوم الحوادث',
  [LANG_KEY.MECHANICAL_SERVICE_FEES_CURRENCY]: 'عملة رسوم الخدمة الميكانيكية',
  [LANG_KEY.VACATION_FEES_CURRENCY]: 'عملة رسوم العطلات',
  [LANG_KEY.VEHICLE_PRIVATE_FEES_CURRENCY]: 'عملة رسوم المركبة الخاصة',
  [LANG_KEY.VEHICLE_TYPE_FEES_CURRENCY]: 'عملة رسوم نوع المركبة',
  [LANG_KEY.LATE_NIGHT_FEES_CURRENCY]: 'عملة رسوم الليل المتأخر',
  [LANG_KEY.MINIMUM_FEES_CURRENCY]: 'عملة الحد الأدنى للرسوم',
  [LANG_KEY.FEES_PER_KM_CURRENCY]: 'الرسوم لكل كم عملة',
  [LANG_KEY.EASY_ROAD_FEES_CURRENCY]: 'عملة رسوم الطريق السهل',
  [LANG_KEY.MEDIUM_ROAD_FEES_CURRENCY]: 'عملة رسوم الطرق المتوسطة',
  [LANG_KEY.DIFFICULT_ROAD_FEES_CURRENCY]: 'عملة رسوم الطرق الصعبة',
  [LANG_KEY.ACCEPT]: 'قبول',
  [LANG_KEY.ACCEPTED]: 'مقبول',
  [LANG_KEY.ESTIMATED_FEES_CURRENCY]: 'عملة الرسوم التقديرية',
  [LANG_KEY.ADDITIONAL_COST_CURRENCY]: 'عملة الرسوم الإضافية',
  [LANG_KEY.POLICY_TRANSACTION_FEES]: 'رسوم المعاملات البوليصة',
  [LANG_KEY.POLICY_TRANSACTION_COMMISSION]: 'عمولة معاملات السياسة',
  [LANG_KEY.POLICY_TRANSACTION_BROKER_COMMISSION]: 'عمولة وسيط المعاملات التجارية',
  [LANG_KEY.FORBIDDEN]: '403 ممنوع',
  [LANG_KEY.YOU_HAVE_NO_ACCESS_ON_THIS_PAGE]: 'ليس لديك وصول إلى هذه الصفحة',
  [LANG_KEY.BACK_TO_HOME_PAGE]: 'العودة إلى الصفحة الرئيسية',
  [LANG_KEY.USERS_PROFILE]: 'ملف تعريف المستخدمين',
  [LANG_KEY.ADD_COMPANY_EMAIL]: 'أضف بريد الشركة الإلكتروني',
  [LANG_KEY.EMAIL]: 'البريد الإلكتروني',
  [LANG_KEY.COMPANIES_EMAIL]: 'بريد الشركات',
  [LANG_KEY.BIILING_RULE]: 'قاعدة الفواتير',
  [LANG_KEY.CANCELED]: 'ألغيت',
  [LANG_KEY.ACTIVE]: 'نشيط',
  [LANG_KEY.SELECT]: 'تحديد',
  [LANG_KEY.MONEY_CONVERSION]: 'تحويل الأموال',
  [LANG_KEY.ADD_MONEY_CONVERSION]: 'إضافة تحويل الأموال',
  [LANG_KEY.FROM]: 'من',
  [LANG_KEY.TO]: 'إلى',
  [LANG_KEY.RATE]: 'معدل',
  [LANG_KEY.FROM_CURRENCY]: 'من العملة',
  [LANG_KEY.TO_CURRENCY]: 'إلى العملة',
  [LANG_KEY.WEBSITE]: 'موقع الكتروني',
  [LANG_KEY.IS_DEFAULT]: 'هو الافتراضي',
  [LANG_KEY.NO]: "لا",
  [LANG_KEY.PLEASE_SELECT_CONTACT_TO_SHOW_DETAILS]: 'الرجاء تحديد جهة اتصال لإظهار التفاصيل',
  [LANG_KEY.ADD_NEW_CONTACT]: 'إضافة جهة اتصال جديدة',
  [LANG_KEY.SEARCH_BY_NAME]: 'البحث عن طريق الإسم',
  [LANG_KEY.COMPANY_MAIN_EMAIL]: 'البريد الإلكتروني الرئيسي للشركة',
  [LANG_KEY.MAIN_EMAIL]: 'البريد الإلكتروني الرئيسي',
  [LANG_KEY.ADD_BRAND]: 'أضف العلامة التجارية',
  [LANG_KEY.PLEASE_SELECT_BRAND_TO_SHOW_ITS_MODELS]: 'الرجاء تحديد العلامة التجارية لإظهار موديلاتها',
  [LANG_KEY.VEHICLES]: 'مركبات',
  [LANG_KEY.ADD_MODEL]: 'أضف النموذج',
  [LANG_KEY.MODEL]: 'نموذج',
  [LANG_KEY.ADD_SECONDARY_EMAIL]: 'أضف بريد إلكتروني ثانوي',
  [LANG_KEY.PLEASE_SELECT_COMPANY_T0_VIEW_SECONDARY_EMAILS]: 'يرجى تحديد شركة لعرض البريد الإلكتروني الثانوي',
  [LANG_KEY.SHOW_EMAILS]: 'إظهار البريد الإلكتروني',
  [LANG_KEY.INSURANCE_CATEGORY]: 'فئة التأمين'

};
